### ISSUE TITLE
Ability to disable authentication

### ISSUE THREAD

**Issue by leo** [otterthecat/mongonaut#11]
We're using your package at [Muffin](http://muffin.cafe) to import sample data within our [Yeoman generator](https://github.com/small-cake/generator). Testing the generator on different devices showed that new MongoDB instances neither have an username nor a password set.

So when trying to import things, mongonaut currently requires a password and username to be set in the `config` property. But since there's no authentication set on the MongoDB instance, it always returns an error when trying to insert data.

Could you please remove the params for username and password if they're not set it `config`? :blush:

**Comment by otterthecat** [comment]
Sounds reasonable to allow a no auth option.

I'll try to have an update over the weekend.
Thanks for the suggestion!

**Comment by leo** [comment]
@otterthecat Perfect, thank you! :blush:

**Comment by otterthecat** [comment]
Merged changes. Mongonaut is now at v2.1.0

If you have any issues, let me know, and thanks again for the input!

**Comment by leo** [comment]
@otterthecat Thank you sooo much, again! :blush: Exactly what I needed.
