### ISSUE TITLE
Feature for exporting data

### ISSUE THREAD

**Issue by leo** [otterthecat/mongonaut#13]
I understand if this might seem like a huge feature request, but I would be really happy if mongonaut could also support exporting certain collections using [mongoexport](https://docs.mongodb.org/manual/reference/program/mongoexport/). As far as I know, the scheme is pretty much identical to `mongoimport`. :blush:

The biggest difference is probably that `mongoexport` will return data. If you could ask me, the best way to handle those strings is to simply pass it to the resolver of the Promise, so that the user can handle it by itself (since `mongoexport` outputs the data to `stdout` by default, this probably won't be that hard):

``` js
mongonaut.export('pages')
  .then(function (fields) {
    // "fields" now contains the content of the collecting as string or JS object
  });
```

Code for exporting multiple collections:

``` js
mongonaut.export(['pages', 'users'])
  .then(function (collections) {
      // the same as above, but "collections" will now be...
      // ...an array containing the content of all collections
  });
```

---

Here's a usecase example: Currently, I'm using that whole command to export sample data at [muffin](https://github.com/small-cake/generator) after making changes to it:

```
mongoexport --db <db_name> --collection <collection_name> --out output.json --jsonArray --pretty
```

As you can see, the "db_name" and "collection_name" also always need to be replaced. But since the generator already knows the name of the DB (by retrieving it from the `.env` file), it would be so much easier create a custom command for it:

```
// Exporting a single collection
yo muffin:export pages
```

```
// Exporting all collections
yo muffin:export
```

By the way: The developers behind muffin won't be the only ones using this feature to export data. Even devs that are creating websites using muffin will use the command to transfer data between different environments/devices.

Because of that, it might also be cool if mongonaut could export all the data within a certain DB:

``` js
mongonaut.export()
  .then(function (allCollections) {
      // "allCollections" will be an array containing the data of all collections
  });
```

**Comment by otterthecat** [comment]
The request seems to make sense - truth be told, I made this to automate some processes I have, and I never needed an export, so it wasn't 'even considered.

Let me give this an approach a little thought - as I'm going to be a little busy the next couple days, but should have something soon.

And  thanks for all the input. It' s cool to know something I wrote is getting use outside of myself :)

**Comment by leo** [comment]
@otterthecat Awesome! :blush:

**Comment by leo** [comment]
@otterthecat Just so you know: I'll deprecate [this](https://github.com/small-cake/generator) in favour of making [this](https://github.com/small-cake/core) a command line interface (so we'll use mongonaut there) :blush:

**Comment by otterthecat** [comment]
Still have things going on, but will start to address over the weekend.

Some current thoughts on it:
- While the `mongoexport` command allows for outputting to a file, I think I would rather return the data as a stream, so as to leave it up to the developer what they want to do with it, keeping the required options to a minimum.
- `mongoexport` also allows for passing a query to export more specific data (say, tracking a specific page). It may be useful to support this as well.
- If the expectation of using `mongoexport` is for backups, it seems `mongodump` [is the better option](https://docs.mongodb.org/manual/reference/program/mongoexport/#considerations). Going this route would also imply using `mongorestore` as well.
- Going with the suggested `.export([collection1, collection2])`, it presents an interesting side effect of essentially bypassing Mongonaut's config object and instead use whatever is passed in the array argument.

None of this means I absolutely will/won't do anything, just mores a place to document thoughts and leave it open to comment.

**Comment by leo** [comment]
> Still have things going on, but will start to address over the weekend.

Great to hear! :+1: 

> While the mongoexport command allows for outputting to a file, I think I would rather return the data as a stream, so as to leave it up to the developer what they want to do with it, keeping the required options to a minimum.

I'd be fine with that too, makes sense!

> mongoexport also allows for passing a query to export more specific data (say, tracking a specific page). It may be useful to support this as well.

:ok_hand:

> If the expectation of using mongoexport is for backups, it seems mongodump is the better option. Going this route would also imply using mongorestore as well.

Definitely not.

At least WE will be using using it to export the data from a certain website (using the CLI that I'm [currently building](https://github.com/small-cake/core)), so that it can easily be added to a Git repo (when talking open source, for example), or imported again on a different environment.

As an example: When developing a site locally (before deploying it), it will be very easy to transfer the content of the site to a different device, if multiple people are working on a single site.

Since `mongodump` creates binary files, it's not very useful in those cases. Just exporting the contents as JSON files seems much cleaner and of course easier editable to me.

> Going with the suggested .export([collection1, collection2]), it presents an interesting side effect of essentially bypassing Mongonaut's config object and instead use whatever is passed in the array argument.

I'd say it should simply be extended (so that user, db and password stay and only the collection string will be overwritten by an array).

**Comment by leo** [comment]
Just added the first half of the features I was talking about: The neat `import` [subcommand](https://github.com/muffinjs/app/blob/master/bin/import.js) (just so you know what I'm talking about). As soon as mongonaut is able to handle exports, I will be able to implement the other half: Exporting.

**Comment by otterthecat** [comment]
Gotcha. I did start adding the export functionality, but it's not done yet. Should have it at latest by end of the week.

**Comment by otterthecat** [comment]
sorry for radio silence - work and life have been a bit overwhelming lately, and it won't get better until after first week of may.

If I'm lucky I'll get to it this weekend, but if not, then thanks for your patience.

**Comment by leo** [comment]
@otterthecat No rush! This is open source, not a conversation with investors. Please take as much time as you need for this! I hightly appreciate that you're even putting that much effort into it at all. :blush:

Besides of that, I have no idea what you're doing or who you are, but it looks like you've published a lot of great open source work (most of which hasn't been noticed yet). So I don't want to play the preacher here, but if you're overwhelmed or not fully happy with your job, I highly recommend switching to a different one (I did exactly that recently and started freelancing). You have the skills! :wink:

**Comment by otterthecat** [comment]
Hello! Sorry it's been a while!

So I just did a quick first pass as adding `export` functionality.
You can check out the changes in [this branch](https://github.com/otterthecat/mongonaut/commit/c92a5cae5ccc9182126f19a21cefc2d48694f6f5)

I made it as simple as possible (for the time being at least): 
- if you don't pass an argument to `export()` then it will export the collection that you set when configuring the `mongonaut` instance.
- if you pass it a string with the name of a differnt collection, it shoud export that collection
- if you pass it an array of collection names, it should export each one (I haven't actually tested this yet, but I think it'll work as is)
- the name of the created json file will match the name of the collection.

Feel free to try the changes and see if they are in the lines of what you were expecting.

Again, ths is a first pass, and needs to cleaning up (and passing unit tests), it also may need to be refactored to acoomodate `MongoDB v 2+` as well as `MongoDB v 3` as they have slight difference regarding flags to the `mongoexport` command.

I also would like to support returning a stream so a developer can apply transforms to the exported data, but I'll probably make a new issue for that.

Lastly - thanks for the patience and kind words. I'm actually already a developer. The mentioning of being "overwhelemed" was due to a lot of changes here, and in fact I'm moving across the country in a couple weeks, but will try to knock this issue out in the next few days (schedule permitting).

Thanks!

**Comment by otterthecat** [comment]
Oops, hit wrong button - didn't meant to close
