### ISSUE TITLE
Use "Releases" for changelog

### ISSUE THREAD

**Issue by leo** [otterthecat/mongonaut#14]
My personal recommendation is to use [releases](https://github.com/blog/1547-release-your-software) for the changelog and remove it from the `README.md` file.

**Comment by otterthecat** [comment]
Funny thing - yesterday, after I pushed the new version, I said to myself "that change log list is getting long. Next release I should extract it!"

Haven't heard of Releases, will check it out.

Thanks for the suggestion!

**Comment by leo** [comment]
:ok_hand: :blush:

**Comment by otterthecat** [comment]
Opted to just make a changelog file

issue closed with:

 https://github.com/otterthecat/mongonaut/commit/afe3d554324ef8de21ebe7e27cfc0ec88402ec19
