### ISSUE TITLE
add option for numInsertionWorkers

### ISSUE THREAD

**Issue by Freundschaft** [otterthecat/mongonaut#19]
https://docs.mongodb.com/v3.0/reference/program/mongoimport/#cmdoption--numInsertionWorkers

could greatly affect performance, it would be cool to have an option for that in mongonaut

**Comment by otterthecat** [comment]
Honestly, when I originally wrote mongonaut, my use case was for pretty small JSON files. However, your suggestion sounds like a good idea to include.

**Comment by Freundschaft** [comment]
the feature is actually quite simple: https://github.com/gfnork/mongonaut/commit/fdecc564d0b117083574614136e9c9e5265ef91b#diff-32a8cfb1af74860f3233cd24dcd57fadR17

**Comment by otterthecat** [comment]
If you submit a PR with this feature only  & update the tests, I can get this one in. Otherwise I can do it later.

**Comment by Freundschaft** [comment]
can do later this week, right now I'm also a little loaded

**Comment by otterthecat** [comment]
Don't worry about it, I can get this done.
