### ISSUE TITLE
Error: stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by Freundschaft** [otterthecat/mongonaut#20]
the maxbuffer sometimes runs out for stderr, maybe use spawn instead of exec?

**Comment by Freundschaft** [comment]
I have replaced exec with spawn, but unfortunately some api changes need to be made, as far as I can see they make sense though
https://github.com/gfnork/mongonaut/commit/fdecc564d0b117083574614136e9c9e5265ef91b

**Comment by otterthecat** [comment]
Thanks for forging ahead on this. Let me look deeper at your changes over the weekend with a clear head. It's been a long week and my brain is melting at the moment.

**Comment by Freundschaft** [comment]
no worries, tell me when you have made your mind up, then I can create a PR

**Comment by otterthecat** [comment]
A couple questions:

**Comment by Freundschaft** [comment]
yes? :)

**Comment by otterthecat** [comment]
A couple questions:
[Edited because I fat fingered "enter" before I wrote anything :( ]

I'm probably missing something, but what are you specfically ensuring you're cleaning up with this filter?

Also, while I'm ok with potential API changes for switching to spawn() over exec(), isn't there a potential issue where the promise.all() could be resolved before the all the imports are completed?
I know we can listen to the stream, but I'm a bit concerned it may start to get confusing.

**Comment by Freundschaft** [comment]
the main issue for me was that during import a bunch of errors with some invalid records would occur (e.g. in my case I have a geoindex on a couple of fields, and sometimes the mongoimport data source latlng would be out of bounds), mongoimport just skips these records, but outputs an error message to stderr. If the amount of records that are problematic add up and exceed maxbuffer, then exec just quits and cancels the mongoimport. 
That's the main reason for me to require usage of spawn instead of exec.
I know its possible to pipe stderr to dev null, but that doesnt work under all platforms

**Comment by otterthecat** [comment]
Apologies for not being super quick in getting back to you - current job is requiring a lot of hours lately.

Anyway, I don't think I'm being clear - my concern overall is that internally, Mongonaut returns a promise after all the imports are completed (easier to do with exec's callback). Switching to spawn, while more efficient, could make it more difficult to be certain the imports are completed.

My expectation after an import, chaining `.then()` would be that all imports are completed.

I'm all for switching to spawn, I just want to minimize any negative impact. Listening to the stream events from each spawn is a possibility, but seems like that would be awkward to manage once they get beyond a certain number. Though at the moment, I admit I don't have a better idea.

**Comment by Freundschaft** [comment]
no worries, I also have a day job requiring my attention :)

I understand that concern, but I'm not even sure its a good idea to offer multiple import from mongonaut, because as far as I know mongoimport doesnt have that functionality natively implemented.
Why should mongoimport take care of multiple file import?
I would rather let users of the library do stuff like

Promise.resolve(arrayOfFiles)
.map(mongonaut.import)
.then(function(result){
   //do whatever with the result, listen for events, etc.
})

Of course it would be also possible to replace this line here:

https://github.com/gfnork/mongonaut/commit/fdecc564d0b117083574614136e9c9e5265ef91b#diff-27a1c86133de4310373decfdad200a91R22

with a .on('end',resolve), which would mimic the current behavior, but in that case, the output of stderr/stdout would need to be stored in a different manner.

**Comment by Freundschaft** [comment]
the problems I have with exec is that in case mongoimport reports errors (e.g. because some entries cant be imported) and th emaxbuffer

**Comment by otterthecat** [comment]
using `.on('close', resolve)` was pretty much what I was thinking of, as it would give an exit code at least. Going further, we could maybe add `stderr.on('data', reject)` to at allow for handling of errors?

It didn't occurr to me to use `.map` on a list of files to import... I like the idea of moving to that approach.

**Comment by Freundschaft** [comment]
yes, that would work of course, but then users of the API would never be able to actually read the content of stderr or stdout

**Comment by otterthecat** [comment]
Issue not forgotten (honest). This will be part of a complete rewrite I'll be doing for v3.0.0
