### ISSUE TITLE
Add import's --drop and --quiet options

### ISSUE THREAD

**Issue by daniel-rodrigue** [otterthecat/mongonaut#21]
Please add support for import's `--drop` option:

> Modifies the import process so that the target instance drops the collection before importing the data from the input.

And `--quiet` option:

> Runs the mongoimport in a quiet mode that attempts to limit the amount of output.

**Comment by otterthecat** [comment]
Adding `--drop` will be an inherited feature from [spawngo](https://github.com/otterthecat/spawngo), however there will be no direct configuration for `--quiet`, as you can simply opt to not do anything with the process output.
